services:
  - type: web
    name: najmat-alibdaa
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: najmat-alibdaa-db
          property: connectionString

databases:
  - name: najmat-alibdaa-db
    databaseName: najmat_alibdaa
    user: najmat_user
